category: 'ohta'
task: 'interhand'
subject: 'train/prior_learning_data' 
experiment: 'ohta'
phase: 'train'

##############################################
## Data Configuration

train:
  dataset_module: 'core.data.interhand.train'
  dataset: 'interhand_train'
  maxiter: 3000000
  maxepoch: 20 # 4000000000
  lr_decay_rate: 0.1
  lr: 0.0005
  lr_smpl_body: 0.00005
  lossweights:
    lpips: 1.0
    l1: 1.0
    sil: 1.0
    iou3d: 1.0
    shadow_reg: 0.1
  accum_iter: 8
  save_model_interval: 20000
  log_info: 20

progress:
  dataset_module: 'core.data.interhand.train'
  dataset: 'interhand_test'
  subject: 'train/prior_learning_data'
  skip: 100
  dump_interval: 20000


##############################################
## Modules Configuration
smpl_cfg:
  model_type: 'mano'  # if you use smplh or smplx, make sure to adjust data loaders accordingly
  flat_hand_mean: True
  gender: 'neutral'
  use_pca: False
  is_rhand: True
  center_id: 4
  scale: 10.
  seal: True
  distal: True
  num_betas: 10
  model_path: 'third_parties'
  pairof_name: 'core.nets.ohta.pairof.pairof_render'
  pairof_pretrain: 'third_parties/pairof/out/pretrained_pairof/pairof.ckpt'
  neighbor: 4
  n_samples: 256
  extended_dist: 0.01
  local_en_dim: 64
  part_en_dim: 64
  en_part_normal: True
  fusion_pool: False
  decoder_layer: [4, 128]
  inbox_feat: False
  pre_train: ''
  level_set: 0.5
  bbox_padding: 2.0
  sigma: 0.05
  soft_beta: 0.05
  softmax_out: True
  manohd: 2
  lbs_weights: 'third_parties/smplx/out/pretrained_lbs_weights/lbs_weights.pth'
  global_sample_num: 4096

deform_network:
  module: 'core.nets.ohta.deform_network.deform_network'
  feature_vector_size: 78 # 45
  d_in: 3
  d_out: 3
  dims: [128, 128, 128, 128]
  multires: 6
  embedder: 'core.nets.ohta.embedders.embedder'
  hidden_feats: 256
  hidden_layers: 6
  in_feat: 35
  cond_feats: 135
  num_verts: 12337
  normal_frame: False

color_network:  
  module: 'core.nets.ohta.canonical_rendering_network.rendering_sdf'
  d_feature: 161
  code_dim: 128
  mode: 'feat'
  d_in: 0
  d_out: 16
  multires_view: 0
  multires_normal: 0
  multires_pos: 0
  d_hidden: 256
  n_layers: 4
  dict_list: [512, 1024, 2048, 4096]

shadow_network:
  module: 'core.nets.ohta.canonical_rendering_network.rendering_sdf'
  d_feature: 191
  code_dim: 128
  mode: 'feat'
  d_in: 0
  d_out: 16
  multires_view: 0
  multires_normal: 0
  multires_pos: 0
  d_hidden: 256
  n_layers: 4
  dict_list: [256]

network_module: 'core.nets.ohta.network'

embedder:
  module: "core.nets.ohta.embedders.fourier"

non_rigid_embedder:
  module: "core.nets.ohta.embedders.hannw_fourier"

rendering_network:
  module: 'core.nets.ohta.canonical_rendering_network.rendering_sdf'
  d_feature: 128
  code_dim: 128
  mode: 'feat'
  d_in: 0
  d_out: 3
  multires_view: 0
  multires_normal: 0
  multires_pos: 0
  d_hidden: 256
  n_layers: 4


##############################################
## Misc
total_bones: 16
bgcolor: [0., 0., 0.]
resize_img_scale: 1.0
bbox_offset: 0.01
resume: False
load_net: latest
ignore_deform: False # False # True
ignore_shadow_network: False # False
ignore_non_rigid_motions: True
ignore_pose_decoder: True
ignore_smpl_body: 'encoder'
patch:
  N_patches: 2 
  size: 32 
N_samples: 64
N_importance: 32
N_3d: 0
render_frames: 100
run_geo: False
chunk: 100000 
netchunk_per_gpu: 100000 
interhand:
  fps: 5


one_shot:
  enable: False
